### PR TITLE
Return 202 for accepted, but not delivered notif.

### PR DESCRIPTION
**Pull request by jrconlin**
resolves https://github.com/mozilla-services/pushgo/issues/206

@kitcambridge r?

### CODE REVIEW

**Comment by bbangert** [comment]
You forgot to update the test that tests this, as a result it fails Travis. :wink:

**Comment by kitcambridge** [comment]
Looks like `TestEndpointDelivery` needs to be updated.

**Comment by jrconlin** [comment]
resolved collision, and fixed the Makefile dep that caused the missing test detection.

**Comment by kitcambridge** [comment]
r+

**Pull request merged**
